# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SecondRung' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SecondRung

  pod 'Firebase/Core'
  pod 'FirebaseUI/Auth'
  pod 'Firebase/Database'
  pod 'OAuthSwift', '~> 1.2.0'

  target 'SecondRungTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
